### ISSUE TITLE
Synthetic data and results on real dataset? such as NYU

### ISSUE THREAD

**Issue by Minotaur-CN** [shrekei/RandomDecisionForest#2]
Dear Hui,
Very appreciate your code on hand pose estimation@https://github.com/shrekei/RandomDecisionForest. 1 . I had a problem on your implementation on your synthetic data.

	for (int i = 0; i < mtxDepthPoints.rows; i++)
	{
		for (int j = 0; j < mtxDepthPoints.cols; j++)
		{
			float x, y, z;
			fread(&x, sizeof(float), 1, pFile);
			fread(&y, sizeof(float), 1, pFile);
			fread(&z, sizeof(float), 1, pFile);
			mtxDepthPoints.at<cv::Vec3f>(i, j) = cv::Vec3f(x, y, z);
		}
	}

The depth image "mtxDepthPoints" should be float32 or unsigned char 8uint.
whats <x,y> mean in your synthetic Data?
2. Were your tested your result on NYU training Data?

Regards!

Rui

**Comment by shrekei** [comment]
Dear Rui,


For question1:

"mtxDepthPoints" is actually 3D point cloud, so each point has x, y, z value


In this demo we didn't run on NYD dataset.


Thanks!


Liang Hui

________________________________
发件人: Mino_Qin <notifications@github.com>
发送时间: 2017年2月14日 11:45:33
收件人: shrekei/RandomDecisionForest
抄送: Subscribed
主题: [shrekei/RandomDecisionForest] Results on NYU? (#2)


Dear Hui,
Very appreciate your code on hand pose estimation@https://github.com/shrekei/RandomDecisionForest. 1 . I had a problem on your implementation on your synthetic data.

for (int i = 0; i < mtxDepthPoints.rows; i++)
{
        for (int j = 0; j < mtxDepthPoints.cols; j++)
        {
                float x, y, z;
                fread(&x, sizeof(float), 1, pFile);
                fread(&y, sizeof(float), 1, pFile);
                fread(&z, sizeof(float), 1, pFile);
                mtxDepthPoints.at<cv::Vec3f>(i, j) = cv::Vec3f(x, y, z);
        }
}


The depth image "mtxDepthPoints" should be float32 or unsigned char 8uint.
whats <x,y> mean in your synthetic Data?
2. Were your tested your result on NYU training Data?

Regards!

Rui

―

**Comment by Minotaur-CN** [comment]
Dear Hui,
I will check your code carefully next time !
Thanks for your reply! 


Regards!

Rui
